# Generated by Django 2.0 on 2017-12-16 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('category', models.CharField(default='amateur', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('profile', models.CharField(max_length=16)),
                ('track', models.CharField(max_length=32)),
                ('mode', models.CharField(max_length=32)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Car')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='time',
            unique_together={('time', 'profile', 'car', 'track', 'mode')},
        ),
    ]
